name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goreleaser/goreleaser:v2
      options: --privileged
    environment:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        run: goreleaser release --clean
